-- Tạo catalog
CREATE CATALOG IF NOT EXISTS default;

-- Dùng catalog
USE CATALOG default;

-- Schema 
CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS alert;

CREATE GROUP DE ;
CREATE GROUP BA ;
ALTER GROUP DE ADD USER `minhhaiit1k68@gmail.com` ;

GRANT SELECT, MODIFY ON SCHEMA bronze TO `DE` ;
GRANT SELECT, MODIFY ON SCHEMA silver TO `DE`;

GRANT SELECT ON SCHEMA gold TO `BA`;

-- Admin
GRANT ALL PRIVILEGES ON CATALOG default TO `admins`;
